added a basic member dashboard and a member sign-up link
KnightHacks/forge pull request #25
Opened 2024-12-12 21:18 UTC by gitSean23

# Why

Building this foundational feature lays the groundwork for more additions to the dashboard. It's essentially a template that is WIP but most of the required functionality exists in this PR such as basic display, user retrieval, and security checks. 

# What

Additions have been made in which there is now an existing dashboard within the application. Changes have been made to the member form where the component is now an asynchronous function as it needs to accommodate for the useRouter hook. The router hook is used for returning the user to the home page after a successful submission of the member form. 

# Test Plan

This PR has gone through manual testing as well as format, lint, and typecheck tests. One thing to note is that I did use port 5433 instead of 5432 because my local machine is running something on port 5432. 

Screenshots:
Dashboard display
![image](https://github.com/user-attachments/assets/93fba03c-3fa9-4caa-8a15-d5f4dfdfde2a)

Homepage display (if the user IS a member)
![image](https://github.com/user-attachments/assets/da694f3c-a952-455e-b068-0d3f0d513f80)

Homepage display (if the user IS NOT a member)
![image](https://github.com/user-attachments/assets/dc1d8427-0b7a-47f8-a616-67f1212636b6)

Extra check (in the event the user is not a member in the DB, but they somehow access the dashboard page)
![image](https://github.com/user-attachments/assets/05f169d0-1497-4749-bb8f-03312d5edd54)

Additional Notes:
Keep in mind, the dashboard is still a WIP. Just needed to PR this to add in the critical functionality to the repository before adding anything else.

2024-12-12 21:26 UTC, LightBounded submitted a review, later dismissed
Looks good just needs a few changes.

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/page.tsx
> +    const member = await db.query.Member.findFirst({
Should move this into a public tRPC procedure so its reusable. We'll probably reuse this logic a lot.

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/page.tsx
> +          <main className="container h-screen py-16">
Can you inline a ternary operator or some sort of && logic so that we don't need two return statements.

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/member/components/dashboard-component.tsx
> +  const member = await db
Should probably move this logic into a procedure.

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/member/dashboard/page.tsx
> +        src={"../../../../../blade/public/tk-dashboard-img.svg"}
you can reference static assets in the public folder like /tk-dashboard-img.svg

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/member/dashboard/page.tsx
> +        alt="tk-pic"
Alt messages should probably be a little more descriptive. Something like "A picture of Tech Knight". Avoid acronyms for better accessibility.

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/member/dashboard/page.tsx
> +        src={"../../../../../blade/public/tk-dashboard-img.svg"}
/{static asset name}

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/page.tsx
> +
something like { member && <Component/> }

2024-12-12 21:26 UTC, LightBounded commented on apps/blade/src/app/member/components/dashboard-component.tsx
> +  console.log("Welcome: " + memberFirstName);
Gotta add a lint rule for no console logs in prod. Remove this for now.

2024-12-20 06:26 UTC, TTRAN70 commented on apps/blade/src/app/member/components/dashboard-component.tsx
Please follow the file convention for components to ensure consistency and readability (e.g. Renaming components folder to "_components" and putting it under dashboard folder

2024-12-20 06:26 UTC, TTRAN70 requested changes
Just a minor change and it's all good

2024-12-20 06:52 UTC, TTRAN70 approved these changes

2024-12-20 19:09 UTC, merged