add resume upload button
KnightHacks/forge pull request #34
Opened 2024-12-24 23:09 UTC by anna-sage

# Why

# What

# Test Plan

2025-01-03 21:06 UTC, DVidal1205 commented
looks fire, think we can get a video demo attached?

2025-01-03 21:11 UTC, DVidal1205 requested changes
heat asf, ive only got one small review i can see but be sure to wait for 1 more review.

also, can we extract the button and all of its logic into a component? we will need to use this exact button on @TTRAN70's new member management front end, so that may help a lot to use later and you know the functionality.

2025-01-03 21:11 UTC, DVidal1205 commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +    onError() {
instead of resume sent to bucket, lets say something more user friendly like "Resume successfully uploaded!

2025-01-03 21:13 UTC, DVidal1205 commented
also, can we extract the button and all of its logic into a component? we will need to use this exact button on @TTRAN70's new member management front end, so that may help a lot to use later and you know the functionality.

2025-01-03 22:00 UTC, must108 requested changes
looks pretty good. just a few const/string changes from me

2025-01-03 22:00 UTC, must108 commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +  const MAX_RESUME_SIZE = 5 * 1000000; // 5MB
move to const file

2025-01-03 22:00 UTC, must108 commented on packages/api/src/routers/resume-upload.ts
> +          await s3Client.makeBucket(bucketName, "us-east-1");
make this string const

2025-01-03 22:00 UTC, must108 commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +                message: "Object in FileList is undefined",
this and other zod issues/errors/not user-facing strings can have more consistent punctuation

2025-01-04 04:53 UTC, Lewin-B commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +  const MAX_RESUME_SIZE = 5 * 1000000; // 5MB
You sound like me

2025-01-04 04:53 UTC, Lewin-B commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +    onError() {
Great idea

2025-01-04 04:53 UTC, Lewin-B commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +                message: "Object in FileList is undefined",
Could you give an example?

2025-01-04 04:53 UTC, Lewin-B commented on packages/api/src/routers/resume-upload.ts
> +          await s3Client.makeBucket(bucketName, "us-east-1");
Great catch

2025-01-04 05:00 UTC, DVidal1205 commented on apps/blade/src/app/member/application/_components/member-application-form.tsx
> +  const MAX_RESUME_SIZE = 5 * 1000000; // 5MB
this the chemistry u was talking ab @Lewin-B

2025-01-04 14:32 UTC, DVidal1205 approved these changes

2025-01-04 15:18 UTC, merged